### ISSUE TITLE
Cannot build unit tests of project that imports vue-advanced-cropper

### ISSUE THREAD

**Issue by struchon** [Norserium/vue-advanced-cropper#12]
Since I added vue-advanced-cropper to a project built with webpack, unit tests (ran with `vue-cli-service test:unit`) fail to compile.

```javascript
TypeError: Cannot read property 'startsWith' of undefined
    at styleInject ([...]\dist\webpack:\node_modules\vue-advanced-cropper\dist\index.es.js:68:1)
    at Module../node_modules/vue-advanced-cropper/dist/index.es.js ([...]\dist\webpack:\node_modules\vue-advanced-cropper\dist\index.es.js:87:1)
    at __webpack_require__ ([...]\dist\webpack:\webpack\bootstrap:25:1)
```

The problem stems from the file index.es.js:
```javascript
function styleInject(id, css) {
	if (!css || typeof document === 'undefined') { return; }

	var element;
	var head = document.head || document.getElementsByTagName('head')[0];
	var styleElements  = head.getElementsByTagName('style');

	// To prevent dublicate of the style code during the script reload
	for (var i = 0; i < styleElements.length; i++) {
		if (styleElements[i].innerText.startsWith('/*for=' + id)) {
			element = styleElements[i];
		}
	}
```

Changing
```javascript
if (styleElements[i].innerText.startsWith('/*for=' + id)) {
```
to
```javascript
if (styleElements[i].innerText && styleElements[i].innerText.startsWith('/*for=' + id)) {
```
fixes it.

Is there something else I should be doing to make it work on my end, or is it a bug?

**Comment by Norserium** [comment]
Hello! 

It's pretty strange bug, and it concerns my [other library](https://github.com/Norserium/rollup-plugin-merge-and-inject-css) that I use as a dependency here.

I've added this fix to that library and updated this library to `0.12.5`

**Comment by struchon** [comment]
Thanks for the quick followup! That fixed it.
