### ISSUE TITLE
yarn add vue-advanced-cropper@vue-3 can't be resolved to a satisfying range

### ISSUE THREAD

**Issue by a0s** [Norserium/vue-advanced-cropper#278]
> yarn add vue-advanced-cropper@vue-3          
➤ YN0027: vue-advanced-cropper@vue-3 can't be resolved to a satisfying range
➤ YN0001: Error: vue-advanced-cropper@vue-3 isn't supported by any available resolver
    at Pd.getResolverByDescriptor (/Users/a0s/my/proj/proj-frontend/.yarn/releases/yarn-4.2.2.cjs:141:1698)
    at Pd.bindDescriptor (/Users/a0s/my/proj/proj-frontend/.yarn/releases/yarn-4.2.2.cjs:141:1083)
    at D8 (/Users/a0s/my/proj/proj-frontend/.yarn/releases/yarn-4.2.2.cjs:392:9401)
    at /Users/a0s/my/proj/proj-frontend/.yarn/releases/yarn-4.2.2.cjs:392:8782
    at C (/Users/a0s/my/proj/proj-frontend/.yarn/releases/yarn-4.2.2.cjs:392:7133)
    at g2 (/Users/a0s/my/proj/proj-frontend/.yarn/releases/yarn-4.2.2.cjs:392:8462)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/a0s/my/proj/proj-frontend/.yarn/releases/yarn-4.2.2.cjs:393:531
    at async Promise.all (index 0)
    at async /Users/a0s/my/proj/proj-frontend/.yarn/releases/yarn-4.2.2.cjs:393:488

**Comment by Norserium** [comment]
@a0s, what's version of `yarn` do you use? Do you have `.yarnrc.yml` file in the project directory?

**Comment by a0s** [comment]
yarn -v
4.2.2

.yarnrc.yml:
```yaml
yarnPath: .yarn/releases/yarn-4.2.2.cjs
nodeLinker: node-modules
```

Seems documentation should be updated, `yarn add vue-advanced-cropper` works as expected:
```
"vue-advanced-cropper": "^2.8.9",
```
